#!/bin/sh
#
# upload the latest solution
# and start hugs on the test case file

n=`ls -d1 a*|sort -n|tail -n1|tr -d a`

account=$1
[ -z "$account" ] && account=g0

scp a${n}/AufgabeFFP${n}*.hs $account:Gruppe/
ssh $account "cd Gruppe && hugs AufgabeFFP${n}_test.hs"
