#!/bin/sh
#
# upload the latest solution
# and start hugs on the test case file

n=`ls -d1 a*|sort -n|tail -n1|tr -d a`

scp a${n}/AufgabeFFP${n}*.hs g0:Gruppe/
ssh g0 "cd Gruppe && hugs AufgabeFFP${n}_test.hs"
